name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NPM_CONFIG_FUND: 'false'
  NPM_CONFIG_AUDIT: 'false'
  NODE_ENV: 'production'

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type checking
        run: pnpm run check

      - name: Run linting
        run: pnpm run lint

      - name: Build application
        run: pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sveltekit-build
          path: .svelte-kit/
          retention-days: 1

  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: sveltekit-build
          path: .svelte-kit/

      - name: Install production dependencies
        run: pnpm install --frozen-lockfile --prod

      - name: Deploy to Cloudflare Workers
        run: pnpm exec wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
